### ISSUE TITLE
html in iOS for links and other tags are hard to format

### ISSUE THREAD

**Issue by masterbee** [FokkeZB/UTiL#34]
hi @FokkeZB,

I am truly enjoying this module since it is really handy and I am experimenting with the attributeString. I am having a bit of a hard time trying to format the text for the following html. I really would like the links to be just a different colour and linkable, but they are alway a noticably smaller text, I was under the impression from your code base that it keeps the labels font size and type as a default.

Thoughts?

```js
  html = "Been having a lot of fun with my photography of late. Still happy with my <a href=\"#Nikon\"><font color=\"#003a76\" face=\"Helvetica-Light\">#Nikon</font></a> <a href=\"#D300S\"><font color=\"#003a76\" face=\"Helvetica-Light\">#D300S</font></a> 5 years later. <a href=\"#quality\"><font color=\"#003a76\" face=\"Helvetica-Light\">#quality</font></a> <a href=\"#greatinvestment\"><font color=\"#003a76\" face=\"Helvetica-Light\">#greatinvestment</font></a> <a href=\"#photography\"><font color=\"#003a76\" face=\"Helvetica-Light\">#photography</font></a> ";

```
![screen](https://cloud.githubusercontent.com/assets/829858/5818086/42f196ce-a080-11e4-9fdb-36378afb0b29.png)

**Comment by FokkeZB** [comment]
That's because of https://jira.appcelerator.org/browse/TC-4991 and the reason why https://github.com/FokkeZB/ti-html2as#usage wraps the whole text in a default font size.

**Comment by masterbee** [comment]
@FokkeZB  - Thanks for the update, so is there a workaround. The lira reference is a bit confusing to the trying to understand.
