### ISSUE TITLE
Window Slide animation in android not working when using xp.ui

### ISSUE THREAD

**Issue by hardikamal** [FokkeZB/UTiL#36]
window animation has not been working while navigating the window. i have placed the slide animation xml's in platform->android->res->anim folder.

**Comment by FokkeZB** [comment]
Please explain more what the exact issue is.

**Comment by hardikamal** [comment]
Need to use Ti.App.Android.R.anim.slide_in_right/left instead of Ti.Android.R.anim.slide_in_right/left

**Comment by FokkeZB** [comment]
There's no such thing on Android:

http://developer.android.com/reference/android/R.anim.html

**Comment by hardikamal** [comment]
my problem is solved....!!! Thanks
For those who want to know
options.activityEnterAnimation = Ti.Android.R.anim.slide_in_left;
options.activityExitAnimation = Ti.Android.R.anim.slide_out_right;

this code is only working for left to right. So if we want window slide from right to left then we have to place custom anim files in the platform->android->res->anim folder and for those custom file to work we have to use

options.activityEnterAnimation = Ti.App.Android.R.anim.slide_in_right;
options.activityExitAnimation = Ti.App.Android.R.anim.slide_out_left;

**Comment by FokkeZB** [comment]
Don't forget `options.animated = false` to disable the default animations.
