### ISSUE TITLE
xp.ui labels in listview itemtemplate

### ISSUE THREAD

**Issue by jvandijk** [FokkeZB/UTiL#38]
Hey @FokkeZB,

Is there a way to use the xp.ui overrides for createLabel in list view templates? Alloy renders those templates in a different way then ordinary labels, making it ignore the module declaration.

I'd still like to use this logic though somehow. Any advice would be appreciated.

**Comment by FokkeZB** [comment]
In short: no

The creation of the views happens on the native side, where it can't require JS/native modules to deliver those views.
